[package]
name = "zk-verifier"
version = "0.0.1"
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.multiversx-sc]
version = "0.66.1"

[dependencies.common]
path = "../common"

[dev-dependencies.multiversx-sc-scenario]
version = "0.66.1"

[dev-dependencies]
ed25519-dalek = "2.1.1"
