[package]
name = "contracts-workspace"
version = "0.0.0"
edition = "2021"
publish = false

[workspace]
resolver = "2"
members = [
    "common",
    "scheduler",
    "scheduler/meta",
    "keeper-registry",
    "keeper-registry/meta",
    "rewards",
    "rewards/meta",
    "ping",
    "ping/meta",
    "noop",
    "noop/wasm",
]

[workspace.dependencies]
multiversx-sc = "0.63.0"
multiversx-sc-meta-lib = "0.63.0"
multiversx-sc-scenario = "0.63.0"
multiversx-sc-wasm-adapter = "0.63.0"
common = { path = "common" }
